services:
  - type: web
    name: telegram-test-series-bot
    runtime: docker

    dockerfilePath: ./Dockerfile

    autoDeploy: true

    healthCheckPath: /health

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: API_ID
        sync: false

      - key: API_HASH
        sync: false

      - key: MONGO_URL
        sync: false

      - key: ADMIN_IDS
        sync: false


      - key: DATABASE_CHANNEL_ID
        sync: false

      - key: PAYMENT_VERIFY_CHANNEL_ID
        sync: false

      - key: USER_ACTIVITY_CHANNEL_ID
        sync: false

      - key: PAID_USER_CHANNEL_ID
        sync: false

      - key: FORCE_JOIN_CHANNELS
        sync: false

      - key: GOOGLE_SHEET_URL
        sync: false

      - key: GOOGLE_SCRIPT_URL
        sync: false

      - key: EXTRACT_MAX_RETRIES
        value: "2"

      - key: SEND_EXTRACTED_HTML
        value: "false"

      - key: PORT
        value: "10000"

      - key: PYTHONUNBUFFERED
        value: "1"

    plan: free
